/**
 * Sidebar reproducing the Super site's navigation.
 *
 * Generated by scripts/gen_sidebar.py from super-salvage/super_nav.json.
 * Super's arrangement (12 sections) is hand-curated and differs from the
 * Notion tree (4 sections), so it is the sidebar that is authoritative here.
 *
 * Do not edit by hand — regenerate instead.
 */

module.exports = {
  docs: [
    "home",
    {
      type: 'category',
      label: "What Is Giveth?",
      // Super used the Lucide icon 'FileQuestion'
      link: { type: 'doc', id: "what-is-giveth" },
      collapsed: true,
      items: [
        "about-giveth",
        "getting-started",
        "dao-structure",
        "zero-fees",
        "brandbook",
      ],
    },
    {
      type: 'category',
      label: "Giveth Principles",
      // Super used the Lucide icon 'HeartHandshake'
      collapsed: true,
      items: [
        "code-of-conduct",
        "community-communications-guide",
        "giveth-community-covenant",
      ],
    },
    {
      type: 'category',
      label: "Giveth Processes",
      // Super used the Lucide icon 'AudioWaveform'
      collapsed: true,
      items: [
        "advice-process",
        "governance-process",
      ],
    },
    {
      type: 'category',
      label: "Projects Guide",
      // Super used the Lucide icon 'BookKey'
      collapsed: true,
      items: [
        "create-a-project",
        "adding-updates-to-your-project",
        "project-quality-assurance-guide",
        "project-verification-processes-and-guidelines",
      ],
    },
    {
      type: 'category',
      label: "Donors Guide",
      // Super used the Lucide icon 'BookOpenCheck'
      link: { type: 'doc', id: "donors-project-guides" },
      collapsed: true,
      items: [
        "making-a-donation",
        "recurring-donations",
        "donating-with-metamask",
      ],
    },
    {
      type: 'category',
      label: "Fundraising Guide",
      // Super used the Lucide icon 'Plus'
      collapsed: true,
      items: [
        "fundraising-campaign-guide-with-giveth",
        "giveth-matching-pool",
        "the-givers-pfp-collection",
        "quadratic-funding",
      ],
    },
    {
      type: 'category',
      label: "Wallets Guide",
      // Super used the Lucide icon 'Wallet'
      collapsed: true,
      items: [
        "multisig-wallets-on-giveth",
      ],
    },
    {
      type: 'category',
      label: "GIVeconomy",
      // Super used the Lucide icon 'HelpingHand'
      link: { type: 'doc', id: "the-giveconomy" },
      collapsed: true,
      items: [
        "giveconomy",
        "givbacks",
        "givstream",
        "givpower",
        "archived-staking-pools",
        "givdrop",
        "givgarden-deprecated",
        "givfarm-deprecated",
      ],
    },
    {
      type: 'category',
      label: "Regen Farms",
      // Super used the Lucide icon 'Wheat'
      collapsed: true,
      items: [
        "regenfarms",
        "regenfarm-contracts",
      ],
    },
    {
      type: 'category',
      label: "Devouch Docs",
      // Super used the Lucide icon 'Check'
      link: { type: 'doc', id: "devouch" },
      collapsed: true,
      items: [
        "what-is-devouch",
        "integrating-devouch",
      ],
    },
    {
      type: 'category',
      label: "Security & Troubleshooting",
      // Super used the Lucide icon 'BookOpen'
      collapsed: true,
      items: [
        "troubleshooting",
        "reporting-a-security-issue-or-vulnerability",
      ],
    },
    // Super used the Lucide icon 'MessageCircleMore'
    "faqs",
    {
      type: 'category',
      label: "Causes",
      link: { type: 'doc', id: "causes" },
      collapsed: true,
      items: [
        "how-it-works",
        "creating-a-cause",
        "for-project-owners",
      ],
    },
  ],
}
