#!/usr/bin/env python3
"""
Generate a Docusaurus sidebar that reproduces the Super site's navigation.

Super's sidebar is hand-curated in its dashboard — 12 sections, 36 pages — and
does not match the Notion tree, which has only 4 top-level sections. Rebuilding
the site faithfully means following Super's arrangement, not Notion's.

Inputs:
    super-salvage/super_nav.json   the recovered Super navigation
    scripts/slug_map.json          Notion title -> Super URL slug
    <export>/export-report.json    what notion_export.py actually produced

Usage:
    python3 scripts/gen_sidebar.py --export build-notion --out sidebarsNotion.js
"""

import argparse
import json
import re
import sys
from pathlib import Path


def slugify(s):
    s = re.sub(r"[^\w\s-]", "", (s or "").lower()).strip()
    return re.sub(r"[\s_-]+", "-", s) or "untitled"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--export", default="build-notion")
    ap.add_argument("--nav", default="super-salvage/super_nav.json")
    ap.add_argument("--map", default="scripts/slug_map.json")
    ap.add_argument("--out", default="sidebarsNotion.js")
    args = ap.parse_args()

    nav = json.loads(Path(args.nav).read_text(encoding="utf-8"))
    smap = json.loads(Path(args.map).read_text(encoding="utf-8"))
    by_title = {k: v for k, v in smap["by_title"].items()}
    # Super slug -> Notion title, to go the other way.
    title_by_slug = {v: k for k, v in by_title.items()}

    report_path = Path(args.export) / "export-report.json"
    if not report_path.exists():
        sys.exit(f"no export report at {report_path} — run notion_export.py first")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    exported = {p["title"]: p["slug"] for p in report["pages"]}

    def resolve(entry):
        """Super nav entry -> exported doc id, or None."""
        title = title_by_slug.get(entry.get("link"))
        doc = exported.get(title) if title else None
        if doc:
            return doc
        cand = slugify(entry.get("label", ""))
        return cand if cand in exported.values() else None

    # Docusaurus only shows a sidebar on docs that appear in one, whereas
    # Super's sidebar was global chrome present on every page. So every doc has
    # to be placed somewhere, or it renders bare.
    #
    # Four Notion section pages are landing pages for a whole area; attach them
    # as the category link for the Super section they correspond to, which both
    # gives them a sidebar and makes the category header clickable.
    CATEGORY_INDEX = {
        "What Is Giveth?": "what-is-giveth",
        "GIVeconomy": "the-giveconomy",
        "Devouch Docs": "devouch",
        "Donors Guide": "donors-project-guides",
    }
    # Causes is live at /donation-agents but was never in Super's sidebar.
    EXTRA_SECTIONS = [
        ("Causes", None, "causes",
         ["how-it-works", "creating-a-cause", "for-project-owners"]),
    ]

    sections = []
    missing = []
    for sec in nav["sidebar"]["links"]:
        label = sec.get("label")
        # Not every top-level entry is a category: Super allows a bare page at
        # the top level of the sidebar (FAQ is one), which has type "page" and
        # an empty list. Emit those as a plain doc entry.
        if sec.get("type") == "page" and not sec.get("list"):
            doc = resolve(sec)
            if doc:
                sections.append((label, sec.get("icon"), [doc], True))
            else:
                missing.append((None, label, sec.get("link")))
            continue
        items = []
        for child in sec.get("list", []):
            doc = resolve(child)
            if doc:
                items.append(doc)
            else:
                missing.append((label, child.get("label"), child.get("link")))
        sections.append((label, sec.get("icon"), items, False))

    for label, icon, index_doc, kids in EXTRA_SECTIONS:
        present = [k for k in kids if k in exported.values()]
        if index_doc in exported.values():
            sections.append((label, icon, present, False, index_doc))

    lines = [
        "/**",
        " * Sidebar reproducing the Super site's navigation.",
        " *",
        " * Generated by scripts/gen_sidebar.py from super-salvage/super_nav.json.",
        " * Super's arrangement (12 sections) is hand-curated and differs from the",
        " * Notion tree (4 sections), so it is the sidebar that is authoritative here.",
        " *",
        " * Do not edit by hand — regenerate instead.",
        " */",
        "",
        "module.exports = {",
        "  docs: [",
    ]
    sections = [s if len(s) == 5 else (*s, CATEGORY_INDEX.get(s[0])) for s in sections]

    # The homepage is a doc too, and needs a sidebar like every other page.
    lines.append('    "home",')

    for label, icon, items, is_page, index_doc in sections:
        if not items and not index_doc:
            continue
        if is_page:
            if icon:
                lines.append(f"    // Super used the Lucide icon {icon!r}")
            lines.append(f"    {json.dumps(items[0])},")
            continue
        lines.append("    {")
        lines.append("      type: 'category',")
        lines.append(f"      label: {json.dumps(label)},")
        if icon:
            lines.append(f"      // Super used the Lucide icon {icon!r}")
        if index_doc:
            lines.append(f"      link: {{ type: 'doc', id: {json.dumps(index_doc)} }},")
        lines.append("      collapsed: true,")
        lines.append("      items: [")
        for it in items:
            lines.append(f"        {json.dumps(it)},")
        lines.append("      ],")
        lines.append("    },")
    lines += ["  ],", "}", ""]

    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    placed = sum(len(s[2]) for s in sections)
    print(f"{args.out}: {len([s for s in sections if s[2]])} entries, {placed} pages")

    if missing:
        print(f"\nnot placed ({len(missing)}) — no exported page matched:")
        for sec, lab, link in missing:
            print(f"  [{sec}] {lab}  {link}")

    placed_ids = {i for s in sections for i in s[2]} | {s[4] for s in sections if s[4]} | {"home"}
    unplaced = set(exported.values()) - placed_ids
    if unplaced:
        print(f"\nexported but absent from Super's sidebar ({len(unplaced)}):")
        for u in sorted(unplaced):
            print(f"  {u}")


if __name__ == "__main__":
    main()
