#!/usr/bin/env python3
"""
Generate a Docusaurus sidebar that reproduces the Super site's navigation.

Super's sidebar is hand-curated in its dashboard — 12 sections, 36 pages — and
does not match the Notion tree, which has only 4 top-level sections. Rebuilding
the site faithfully means following Super's arrangement, not Notion's.

Inputs:
    super-salvage/super_nav.json   the recovered Super navigation
    scripts/slug_map.json          Notion title -> Super URL slug
    <export>/export-report.json    what notion_export.py actually produced

Usage:
    python3 scripts/gen_sidebar.py --export build-notion --out sidebarsNotion.js
"""

import argparse
import json
import re
import sys
from pathlib import Path


def slugify(s):
    s = re.sub(r"[^\w\s-]", "", (s or "").lower()).strip()
    return re.sub(r"[\s_-]+", "-", s) or "untitled"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--export", default="build-notion")
    ap.add_argument("--nav", default="super-salvage/super_nav.json")
    ap.add_argument("--map", default="scripts/slug_map.json")
    ap.add_argument("--out", default="sidebarsNotion.js")
    args = ap.parse_args()

    nav = json.loads(Path(args.nav).read_text(encoding="utf-8"))
    smap = json.loads(Path(args.map).read_text(encoding="utf-8"))
    by_title = {k: v for k, v in smap["by_title"].items()}
    # Super slug -> Notion title, to go the other way.
    title_by_slug = {v: k for k, v in by_title.items()}

    report_path = Path(args.export) / "export-report.json"
    if not report_path.exists():
        sys.exit(f"no export report at {report_path} — run notion_export.py first")
    report = json.loads(report_path.read_text(encoding="utf-8"))
    exported = {p["title"]: p["slug"] for p in report["pages"]}

    sections = []
    missing = []
    for sec in nav["sidebar"]["links"]:
        label = sec.get("label")
        items = []
        for child in sec.get("list", []):
            link = child.get("link")
            title = title_by_slug.get(link)
            doc = exported.get(title) if title else None
            if not doc:
                # Fall back to matching the Super label against exported titles.
                cand = slugify(child.get("label", ""))
                doc = cand if cand in exported.values() else None
            if doc:
                items.append(doc)
            else:
                missing.append((label, child.get("label"), link))
        sections.append((label, sec.get("icon"), items))

    lines = [
        "/**",
        " * Sidebar reproducing the Super site's navigation.",
        " *",
        " * Generated by scripts/gen_sidebar.py from super-salvage/super_nav.json.",
        " * Super's arrangement (12 sections) is hand-curated and differs from the",
        " * Notion tree (4 sections), so it is the sidebar that is authoritative here.",
        " *",
        " * Do not edit by hand — regenerate instead.",
        " */",
        "",
        "module.exports = {",
        "  docs: [",
    ]
    for label, icon, items in sections:
        if not items:
            continue
        lines.append("    {")
        lines.append("      type: 'category',")
        lines.append(f"      label: {json.dumps(label)},")
        if icon:
            lines.append(f"      // Super used the Lucide icon {icon!r}")
        lines.append("      collapsed: true,")
        lines.append("      items: [")
        for it in items:
            lines.append(f"        {json.dumps(it)},")
        lines.append("      ],")
        lines.append("    },")
    lines += ["  ],", "}", ""]

    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    placed = sum(len(i) for _, _, i in sections)
    print(f"{args.out}: {len([s for s in sections if s[2]])} sections, {placed} pages")

    if missing:
        print(f"\nnot placed ({len(missing)}) — no exported page matched:")
        for sec, lab, link in missing:
            print(f"  [{sec}] {lab}  {link}")

    unplaced = set(exported.values()) - {i for _, _, items in sections for i in items}
    if unplaced:
        print(f"\nexported but absent from Super's sidebar ({len(unplaced)}):")
        for u in sorted(unplaced):
            print(f"  {u}")


if __name__ == "__main__":
    main()
